[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
agui_core = { path = "crates/agui_core", version = "0.3" }
agui = { path = "crates/agui", version = "0.3" }

agui_test = { path = "crates/agui_test", version = "0.1" }
agui_test_macros = { path = "crates/agui_test_macros", version = "0.1" }

agui_window = { path = "crates/agui_window", version = "0.1" }
agui_winit = { path = "crates/agui_winit", version = "0.1" }
agui_vello = { path = "crates/agui_vello", version = "0.1" }

accesskit = "0.24"
bon = "3.3.2"
intrusive-collections = "0.10"
smallbox = "0.8"
smallvec = "1.14.0"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
typed_floats = "1.0.2"

rand = "0.10"
rustc-hash = "2.1"
slotmap = "1.0"
parking_lot = "0.12"
bitflags = "2.4"
url = "2.4"

futures = "0.3"
futures-util = { version = "0.3", default-features = false }
futures-lite = "2.2"
futures-executor = "0.3"
event-listener = "5.4"
async_cell = "0.2.2"
async-watch = "0.3"
async-lock = "3.3"
async-channel = "2.1"
async-executor = "1"

mockall = "0.14"
criterion = { version = "0.8", features = ["html_reports"] }

lyon = "1.0"
parley = "0.10"
peniko = "0.6"
vello = "0.7"
wgpu = "27"
png = "0.18"

raw-window-handle = "0.6"

winit = "0.30"
pollster = "0.4"

proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[profile.release]
debug = true

[profile.release.package."*"]
debug = true

[profile.dev.package."*"]
opt-level = 3
