[package]
name = "agui_core"
version = "0.3.0"
edition = "2024"
resolver = "2"
description = "The core library of Agui"
homepage = "https://github.com/Stumblinbear/agui"
repository = "https://github.com/Stumblinbear/agui"
keywords = ["gui"]
categories = ["gui"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
bon.workspace = true
fnv.workspace = true
imbl.workspace = true
intrusive-collections.workspace = true
parley.workspace = true
peniko.workspace = true
slotmap.workspace = true
smallbox.workspace = true
typed_floats.workspace = true

# agui_sync.workspace = true

tracing.workspace = true

thiserror.workspace = true

# rand.workspace = true
# rustc-hash.workspace = true
# slotmap.workspace = true
# parking_lot = { workspace = true, optional = true }
# im-rc.workspace = true
# bitflags.workspace = true
# url.workspace = true
# smallbox.workspace = true

# futures-util = { workspace = true, features = ["std", "channel"] }

# lyon.workspace = true

# mockall = { workspace = true, optional = true }

[dev-dependencies]
# agui_macros.workspace = true

# parking_lot.workspace = true

# mockall.workspace = true
criterion.workspace = true

# fnv = "1.0"
# concurrent-queue = "2.4"
