[package]
name = "agui_core"
version = "0.3.0"
edition = "2024"
resolver = "2"
description = "The core library of Agui"
homepage = "https://github.com/Stumblinbear/agui"
repository = "https://github.com/Stumblinbear/agui"
keywords = ["gui"]
categories = ["gui"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
rustc-hash.workspace = true
slotmap.workspace = true

[dev-dependencies]
criterion.workspace = true
