[package]
name = "agui_test"
version = "0.1.0"
edition = "2024"
resolver = "2"
description = "Testing harness for Agui"
homepage = "https://github.com/Stumblinbear/agui"
repository = "https://github.com/Stumblinbear/agui"
keywords = ["gui"]
categories = ["gui"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
agui_core.workspace = true

typed_floats.workspace = true
