[package]
name = "agui_test"
version = "0.1.0"
edition = "2024"
resolver = "2"
description = "Testing harness for Agui"
homepage = "https://github.com/Stumblinbear/agui"
repository = "https://github.com/Stumblinbear/agui"
keywords = ["gui"]
categories = ["gui"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
gpu = ["agui/gpu"]
cpu = ["agui/cpu"]
vello = ["gpu", "dep:agui_vello"]

[dependencies]
agui.workspace = true
agui_core.workspace = true
agui_test_macros.workspace = true

png.workspace = true
typed_floats.workspace = true

agui_vello = { workspace = true, optional = true }
