[package]
name = "agui_primitives"
version = "0.3.0"
edition = "2024"
resolver = "2"
description = "Provides basic widgets for Agui"
homepage = "https://github.com/Stumblinbear/agui"
repository = "https://github.com/Stumblinbear/agui"
keywords = ["gui"]
categories = ["gui"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
agui_render.workspace = true

bon.workspace = true
tracing.workspace = true
typed_floats.workspace = true

[dev-dependencies]
agui_test.workspace = true
