[package]
name = "agui_vello"
version = "0.1.0"
edition = "2024"
resolver = "2"
description = "Vello rendering backend for Agui"
homepage = "https://github.com/Stumblinbear/agui"
repository = "https://github.com/Stumblinbear/agui"
keywords = ["gui", "graphics", "vello"]
categories = ["gui", "graphics", "rendering"]
license = "MIT OR Apache-2.0"

[dependencies]
agui_core.workspace = true
agui_render = { workspace = true, features = ["gpu"] }
agui_window.workspace = true
png.workspace = true
pollster.workspace = true
raw-window-handle.workspace = true
slotmap.workspace = true
vello.workspace = true

[dev-dependencies]
agui_primitives.workspace = true
agui_test = { workspace = true, features = ["vello"] }
async-executor.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
typed_floats.workspace = true
winit.workspace = true
