name: CI
on:
  push:
    branches:
      - main
      - workflow
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - name: Setup | Cache Cargo
        uses: Swatinem/rust-cache@v1

      - name: Build | Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets --all-features -- -D clippy::all

      - name: Build | Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features
